[package]
name = "epd2in13d-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tcp-server"
path = "src/tcp-server.rs"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
anyhow = "1.0.86"
static_assertions = "1.1.0"